version: '2'

services:
  web:
    build: .
    container_name: app
    volumes:
     - "./movabletype:/var/www/html"
    ports:
     - "80:80"
    links:
     - "db:db"

  db:
    image: mysql:5.6
    container_name: db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_USER: coba1
      MYSQL_PASSWORD: pass1
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mova

volumes:
  db_data:
